var fs = require('fs'), // read/write files
    path = require('path'),

    Message = require('../Message.js'),
    FilterTree = require('../FilterTree.js'),
    ScroungeElement = require('../ScroungeElement.js');

var FileInfoBasepage = module.exports = (function () {

  var fileInfoBasepage = {
    basepage : '',
    treeFilter : null,
    scroungeElementObjArr : [],

    // read basepage from disk and return content as string
    getContentStr : function (fn) {
      var basepage = this.basepage;
      if (!basepage) return fn(Message.basepageNotFound());
      fs.readFile(basepage, 'ascii', function (err, res) {
        if (err) return fn(Message.basepageNotFound(basepage));
        fn(null, res);
      });      
    },

    // write basepage content to disk
    writeBasepageStr : function (text, fn) {
      var basepage = this.basepage;
      if (!basepage) return fn(Message.basepageNotFound());
      fs.writeFile(basepage, text, function (err) {
        if (err) return fn(err);
        console.log(Message.writeBasepage(basepage));
        fn(null, basepage);
      });          
    },

    getStrAsScroungeElementObjArr : function (str) {
      return ScroungeElement.getFromStrScroungeElemObjArr(str);
    },

    getScroungeElementFilters : function (scroungeElemObjArr) {
      var treeFilter = this.treeFilter, x;
      for (x = scroungeElemObjArr.length; x--;) {
        if (scroungeElemObjArr[x].trees.length) {
          // only place where addTrees is called...
          treeFilter.addTrees(scroungeElemObjArr[x].trees, scroungeElemObjArr[x].type);
        }
      }
      return treeFilter;
    },

    // returns filters from the basepage by 
    //  - reading the basepage,
    //  - getting scrounge elements from basepage
    //  - getting tree attributes from the scrounge elements
    //  - return each tree definition as a filter
    getFilters : function (fn) {
      var that = this, scroungeElemObjArr, filters;

      if (!that.basepage) return fn(null, null);
      that.getContentStr(function (err, str) {
        if (err) fn(err);
        scroungeElemObjArr = that.getStrAsScroungeElementObjArr(str);
        filters = that.getScroungeElementFilters(scroungeElemObjArr);        
        that.treeFilter = filters;
        fn(null, filters);        
      });
    },

    // get original include element with single element updates generated by treeObj
    refreshIncludeElements : function (treeObjArr, opts, text) {
      var that = this, x, y, scroungeElemObj, fObj;

      for (x = treeObjArr.length; x--;) {
        for (y = treeObjArr[x].fileObjArr.length; y--;) {
          fObj = treeObjArr[x].fileObjArr[y];
          text = that.getWithUpdatedIncludeStr(text, fObj, opts);
        }
      }
      return text;      
    },

    getWithUpdatedIncludeStr : function (str, infoFileObj, opts) {
      var filenameNew = infoFileObj.getCmprNameStr(opts),
          filenameRe = infoFileObj.getFilenameRe();

      return str.replace(filenameRe, '/' + filenameNew);
    },

    // get full include element generated by the treeObj    
    getWithScroungeElemsStr : function (treeObjArr, opts, text) {
      var x, elem, scroungeTag, scroungeElemObj, tObjArr = [],
          scroungeElemObjArr = ScroungeElement.getFromStrScroungeElemObjArr(text);

      for (x = scroungeElemObjArr.length; x--;) {
        scroungeElemObj = scroungeElemObjArr[x];

        tObjArr = treeObjArr.filter(function (treeObj) {
          // treeObj.fileInfoObj type === .js,
          // scroungeElemObj type === js
          return scroungeElemObj.isTreeMatch(treeObj.fileInfoObj);
        });

        elem = scroungeElemObj.getTreeArrAsScroungeElemStr(tObjArr, opts);
        text = text.replace(scroungeElemObj.elem, elem);      
      }
      return text;
    },

    writeTrees : function (treeObjArr, opts, fn) {
      var that = this, elemObjArr;

      if (!that.basepage) return fn(null, null);
      that.getContentStr(function(err, text) {
        if (err) return fn(err);
        // single include element ELSE full tag w all include elements
        if (opts.isUpdateOnly) {
          text = that.refreshIncludeElements(treeObjArr, opts, text);          
        } else {
          text = that.getWithScroungeElemsStr(treeObjArr, opts, text);          
        }

        that.writeBasepageStr(text, fn);
      });
    }
  };

  return {
    getNew : function (opts) {
      var that = Object.create(fileInfoBasepage);
      that.treeFilter = FilterTree.getNew();
      that.basepage = opts.basepage || null;
      return that;
    } 
  };

}());

